### ISSUE TITLE
Github Secrets not working

### ISSUE THREAD

**Issue by namenlosxy** [everglowmc/everglowmc.github.com#1]
Your secrets are not working and thus breaks the whole website since aws can't access the credentials

**Comment by ghost** [comment]
Yeah ik the secrets have been removed due to a security breach

**Comment by namenlosxy** [comment]
They are not working on the website 
`accessKeyId: "",
 secretAccessKey: ""`
 
 causing 
 ```
 DCcreds.js:228 CredentialsError: Missing credentials in config
    at r (https://sdk.amazonaws.com/js/aws-sdk-2.7.16.min.js:35:14473)
    at constructor.getCredentials (https://sdk.amazonaws.com/js/aws-sdk-2.7.16.min.js:35:14992)
    at constructor.<anonymous> (https://sdk.amazonaws.com/js/aws-sdk-2.7.16.min.js:36:1267)
    at constructor.callListeners (https://sdk.amazonaws.com/js/aws-sdk-2.7.16.min.js:37:24535)
    at constructor.emit (https://sdk.amazonaws.com/js/aws-sdk-2.7.16.min.js:37:24273)
    at constructor.emitEvent (https://sdk.amazonaws.com/js/aws-sdk-2.7.16.min.js:37:11655)
    at constructor.e (https://sdk.amazonaws.com/js/aws-sdk-2.7.16.min.js:37:7505)
    at a.runTo (https://sdk.amazonaws.com/js/aws-sdk-2.7.16.min.js:38:30382)
    at constructor.runTo (https://sdk.amazonaws.com/js/aws-sdk-2.7.16.min.js:37:9073)
    at constructor.send (https://sdk.amazonaws.com/js/aws-sdk-2.7.16.min.js:37:8966)```
